/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as GiveRouteImport } from './routes/give'
import { Route as MinistriesRouteImport } from './routes/ministries'
import { Route as PrayerRequestRouteImport } from './routes/prayer-request'
import { Route as SermonsRouteImport } from './routes/sermons'
import { Route as TestimoniesRouteImport } from './routes/testimonies'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as ApiSendEmailRouteImport } from './routes/api/send-email'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as ApiPaymentsInitializeRouteImport } from './routes/api/payments/initialize'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const GiveRoute = GiveRouteImport.update({
  id: '/give',
  path: '/give',
  getParentRoute: () => rootRouteImport,
} as any)
const MinistriesRoute = MinistriesRouteImport.update({
  id: '/ministries',
  path: '/ministries',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayerRequestRoute = PrayerRequestRouteImport.update({
  id: '/prayer-request',
  path: '/prayer-request',
  getParentRoute: () => rootRouteImport,
} as any)
const SermonsRoute = SermonsRouteImport.update({
  id: '/sermons',
  path: '/sermons',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimoniesRoute = TestimoniesRouteImport.update({
  id: '/testimonies',
  path: '/testimonies',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendEmailRoute = ApiSendEmailRouteImport.update({
  id: '/api/send-email',
  path: '/api/send-email',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsInitializeRoute = ApiPaymentsInitializeRouteImport.update({
  id: '/api/payments/initialize',
  path: '/api/payments/initialize',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/give': typeof GiveRoute
  '/ministries': typeof MinistriesRoute
  '/prayer-request': typeof PrayerRequestRoute
  '/sermons': typeof SermonsRoute
  '/testimonies': typeof TestimoniesRoute
  '/volunteer': typeof VolunteerRoute
  '/api/send-email': typeof ApiSendEmailRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/blog/': typeof BlogIndexRoute
  '/events/': typeof EventsIndexRoute
  '/api/payments/initialize': typeof ApiPaymentsInitializeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/give': typeof GiveRoute
  '/ministries': typeof MinistriesRoute
  '/prayer-request': typeof PrayerRequestRoute
  '/sermons': typeof SermonsRoute
  '/testimonies': typeof TestimoniesRoute
  '/volunteer': typeof VolunteerRoute
  '/api/send-email': typeof ApiSendEmailRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/blog': typeof BlogIndexRoute
  '/events': typeof EventsIndexRoute
  '/api/payments/initialize': typeof ApiPaymentsInitializeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/give': typeof GiveRoute
  '/ministries': typeof MinistriesRoute
  '/prayer-request': typeof PrayerRequestRoute
  '/sermons': typeof SermonsRoute
  '/testimonies': typeof TestimoniesRoute
  '/volunteer': typeof VolunteerRoute
  '/api/send-email': typeof ApiSendEmailRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/blog/': typeof BlogIndexRoute
  '/events/': typeof EventsIndexRoute
  '/api/payments/initialize': typeof ApiPaymentsInitializeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/gallery'
    | '/give'
    | '/ministries'
    | '/prayer-request'
    | '/sermons'
    | '/testimonies'
    | '/volunteer'
    | '/api/send-email'
    | '/blog/$slug'
    | '/events/$eventId'
    | '/blog/'
    | '/events/'
    | '/api/payments/initialize'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/give'
    | '/ministries'
    | '/prayer-request'
    | '/sermons'
    | '/testimonies'
    | '/volunteer'
    | '/api/send-email'
    | '/blog/$slug'
    | '/events/$eventId'
    | '/blog'
    | '/events'
    | '/api/payments/initialize'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/gallery'
    | '/give'
    | '/ministries'
    | '/prayer-request'
    | '/sermons'
    | '/testimonies'
    | '/volunteer'
    | '/api/send-email'
    | '/blog/$slug'
    | '/events/$eventId'
    | '/blog/'
    | '/events/'
    | '/api/payments/initialize'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  GiveRoute: typeof GiveRoute
  MinistriesRoute: typeof MinistriesRoute
  PrayerRequestRoute: typeof PrayerRequestRoute
  SermonsRoute: typeof SermonsRoute
  TestimoniesRoute: typeof TestimoniesRoute
  VolunteerRoute: typeof VolunteerRoute
  ApiSendEmailRoute: typeof ApiSendEmailRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  EventsIndexRoute: typeof EventsIndexRoute
  ApiPaymentsInitializeRoute: typeof ApiPaymentsInitializeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/give': {
      id: '/give'
      path: '/give'
      fullPath: '/give'
      preLoaderRoute: typeof GiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ministries': {
      id: '/ministries'
      path: '/ministries'
      fullPath: '/ministries'
      preLoaderRoute: typeof MinistriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayer-request': {
      id: '/prayer-request'
      path: '/prayer-request'
      fullPath: '/prayer-request'
      preLoaderRoute: typeof PrayerRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sermons': {
      id: '/sermons'
      path: '/sermons'
      fullPath: '/sermons'
      preLoaderRoute: typeof SermonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonies': {
      id: '/testimonies'
      path: '/testimonies'
      fullPath: '/testimonies'
      preLoaderRoute: typeof TestimoniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-email': {
      id: '/api/send-email'
      path: '/api/send-email'
      fullPath: '/api/send-email'
      preLoaderRoute: typeof ApiSendEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/initialize': {
      id: '/api/payments/initialize'
      path: '/api/payments/initialize'
      fullPath: '/api/payments/initialize'
      preLoaderRoute: typeof ApiPaymentsInitializeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  GiveRoute: GiveRoute,
  MinistriesRoute: MinistriesRoute,
  PrayerRequestRoute: PrayerRequestRoute,
  SermonsRoute: SermonsRoute,
  TestimoniesRoute: TestimoniesRoute,
  VolunteerRoute: VolunteerRoute,
  ApiSendEmailRoute: ApiSendEmailRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  EventsIndexRoute: EventsIndexRoute,
  ApiPaymentsInitializeRoute: ApiPaymentsInitializeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
